IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [consfix] (
    [fxseq] int NOT NULL IDENTITY,
    [gvars] int NULL DEFAULT 0,
    [itb] int NULL DEFAULT 0,
    [elea] int NULL DEFAULT 0,
    [gp1] int NULL DEFAULT 0,
    [gp2] int NULL DEFAULT 0,
    [gp3] int NULL DEFAULT 0,
    [liba] nvarchar(150) NULL,
    [abg] nvarchar(50) NULL,
    [refa] nvarchar(50) NULL,
    [lgx] int NULL DEFAULT 0,
    [tgx] int NULL DEFAULT 0,
    [codi] int NULL DEFAULT 0,
    [scdrub] nvarchar(50) NULL,
    [lib2] nvarchar(25) NULL,
    [sicur] int NULL DEFAULT 0,
    [inlg] int NULL DEFAULT 0,
    [inth] int NULL DEFAULT 0,
    [datin] datetime2(0) NULL,
    [ddope] datetime2(0) NULL,
    [dfope] datetime2(0) NULL,
    [vendor] nvarchar(250) NULL,
    [version] nvarchar(30) NULL,
    [ethowe] nvarchar(80) NULL,
    [et2owe] nvarchar(80) NULL,
    [inEth] nvarchar(150) NULL,
    [inEt2] nvarchar(150) NULL,
    [inBit] nvarchar(150) NULL,
    [inBi2] nvarchar(150) NULL,
    [inCto] nvarchar(150) NULL,
    [inCt2] nvarchar(150) NULL,
    [it1] int NULL DEFAULT 0,
    [ir1] real NULL DEFAULT CAST(0 AS real),
    [id1] datetime2(0) NULL,
    [datc] datetime2 NULL DEFAULT ((getdate())),
    [eta] int NULL DEFAULT 0,
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_consfix_1] PRIMARY KEY ([fxseq])
);
GO

CREATE TABLE [gtoken] (
    [Idtok] int NOT NULL IDENTITY,
    [idorg] int NULL DEFAULT 0,
    [usrid] nvarchar(450) NULL,
    [ttok] int NOT NULL,
    [xtoken] nvarchar(450) NULL,
    [xts2] nvarchar(450) NULL,
    [xdexp] datetime2(2) NULL,
    [xds2] datetime2(2) NULL,
    [datc] datetime2(2) NULL,
    [obsv] nvarchar(150) NULL,
    CONSTRAINT [PK_gtoken] PRIMARY KEY ([Idtok])
);
GO

CREATE TABLE [gxorga] (
    [idorg] int NOT NULL,
    [tyorg] int NULL DEFAULT 0,
    [raison] nvarchar(450) NOT NULL,
    [sigle] nvarchar(150) NULL,
    [usrid] nvarchar(450) NULL,
    [lbcbl] nvarchar(50) NULL DEFAULT (((0))),
    [slbcbl] nvarchar(50) NULL DEFAULT (((0))),
    [invcde] nvarchar(350) NULL,
    [sitecde] nvarchar(250) NULL,
    [usrcde] nvarchar(450) NULL,
    [nocde] int NULL,
    [sibjx] int NULL DEFAULT 0,
    [schba] int NULL DEFAULT 0,
    [tieba] int NULL DEFAULT 0,
    [hieba] int NULL DEFAULT 0,
    [siagt] int NULL DEFAULT 0,
    [siope] int NULL DEFAULT 0,
    [siclie] int NULL DEFAULT 0,
    [sifour] int NULL DEFAULT 0,
    [sidic] int NULL DEFAULT 1,
    [sigx] int NULL DEFAULT 0,
    [tylib] int NULL DEFAULT 0,
    [dom] int NULL DEFAULT 0,
    [stdom] nvarchar(250) NULL,
    [site] int NULL DEFAULT 0,
    [stsite] nvarchar(250) NULL,
    [jacta] int NULL DEFAULT 0,
    [sjacta] nvarchar(200) NULL,
    [jpoint] int NULL DEFAULT 0,
    [sjpoint] nvarchar(200) NULL,
    [rcm] nvarchar(250) NULL,
    [rifu] nvarchar(250) NULL,
    [ircm] int NULL DEFAULT 0,
    [irfu] int NULL DEFAULT 0,
    [adr] nvarchar(max) NULL,
    [adr2] nvarchar(max) NULL,
    [tyafec] int NULL DEFAULT 0,
    [codi] int NULL DEFAULT 0,
    [cods] nvarchar(100) NULL,
    [natio] int NULL DEFAULT 0,
    [resid] int NULL DEFAULT 0,
    [ibank] int NULL DEFAULT 0,
    [icotis] int NULL DEFAULT 0,
    [itax] int NULL DEFAULT 0,
    [ipaid] int NULL DEFAULT 0,
    [ipays] int NULL DEFAULT 0,
    [iregio] int NULL DEFAULT 0,
    [iprovi] int NULL DEFAULT 0,
    [icity] int NULL DEFAULT 0,
    [icomu] int NULL DEFAULT 0,
    [iquarti] int NULL DEFAULT 0,
    [sbank] nvarchar(150) NULL,
    [scotis] nvarchar(150) NULL,
    [stax] nvarchar(150) NULL,
    [spaid] nvarchar(150) NULL,
    [spays] nvarchar(150) NULL DEFAULT (((0))),
    [sregio] nvarchar(150) NULL,
    [sprovi] nvarchar(150) NULL DEFAULT (((0))),
    [scity] nvarchar(150) NULL,
    [scomu] nvarchar(150) NULL DEFAULT (((0))),
    [squarti] nvarchar(150) NULL,
    [jcity] int NULL DEFAULT 0,
    [photo] nvarchar(max) NULL,
    [photo2] image NULL,
    [photo3] nvarchar(max) NULL,
    [idoca] nvarchar(max) NULL,
    [idocb] nvarchar(max) NULL,
    [idoce] nvarchar(max) NULL,
    [tele] nvarchar(100) NULL,
    [tele2] nvarchar(100) NULL,
    [whatsapp] nvarchar(100) NULL,
    [email] nvarchar(200) NULL,
    [phone] nvarchar(150) NULL,
    [siteweb] nvarchar(200) NULL,
    [rnom] nvarchar(250) NULL,
    [rpnom] nvarchar(250) NULL,
    [cnom] nvarchar(250) NULL,
    [cpnom] nvarchar(250) NULL,
    [cip] nvarchar(200) NULL,
    [liba] nvarchar(150) NULL,
    [liba2] nvarchar(250) NULL,
    [abg] nvarchar(50) NULL,
    [devise] nvarchar(20) NULL,
    [stdevi] nvarchar(20) NULL,
    [spdevi] nvarchar(20) NULL,
    [mdevi] nvarchar(20) NULL,
    [ddeci] int NULL DEFAULT 0,
    [nxplan] int NULL DEFAULT 0,
    [depdat] datetime2(0) NULL,
    [depstr] nvarchar(25) NULL,
    [depexy] int NULL,
    [depexm] int NULL,
    [depexd] int NULL,
    [prvdat] datetime2(0) NULL,
    [prvstr] nvarchar(25) NULL,
    [prvexy] int NULL,
    [prvexm] int NULL,
    [prvexd] int NULL,
    [findat] datetime2(0) NULL,
    [finstr] nvarchar(25) NULL,
    [sirelat] int NULL DEFAULT 0,
    [finexy] int NULL,
    [finexm] int NULL,
    [finexd] int NULL,
    [siparent] bit NULL DEFAULT CAST(0 AS bit),
    [sienfant] bit NULL DEFAULT CAST(0 AS bit),
    [siparain] bit NULL DEFAULT CAST(0 AS bit),
    [sifiheul] bit NULL DEFAULT CAST(0 AS bit),
    [opauto] int NULL DEFAULT 0,
    [cbauto] int NULL DEFAULT 0,
    [prauto] int NULL DEFAULT 0,
    [eta] int NULL DEFAULT 1,
    [selc] bit NOT NULL,
    [datc] datetime2(0) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_gxorga] PRIMARY KEY ([idorg])
);
GO

CREATE TABLE [oarchi] (
    [idorg] nchar(10) NOT NULL,
    [idarc] int NOT NULL IDENTITY,
    [arcid] int NOT NULL,
    [idhie] int NULL DEFAULT 0,
    [starc2] xml NULL,
    [starc3] xml NULL,
    [starc4] xml NULL,
    [starc5] xml NULL,
    [starc6] xml NULL,
    [operi] int NULL DEFAULT 0,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [datc] datetime2(2) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_oarchi] PRIMARY KEY ([idorg], [idarc], [arcid])
);
GO

CREATE TABLE [tiewel] (
    [idtie] int NOT NULL IDENTITY,
    [usrid] nvarchar(450) NULL,
    [usrname] nvarchar(256) NULL,
    [usremail] nvarchar(max) NULL,
    [usrphone] nvarchar(500) NULL,
    [usrsocial] nvarchar(400) NULL,
    [siset] int NULL DEFAULT 0,
    [natio] int NULL DEFAULT 0,
    [resid] int NULL,
    [tymut] int NULL DEFAULT 0,
    [idorg] int NULL,
    [idhie] int NULL DEFAULT 0,
    [idpst] int NULL DEFAULT 0,
    [idgeo] int NULL DEFAULT 0,
    [statut] int NULL DEFAULT 0,
    [sexe] int NULL,
    [sitmat] int NULL DEFAULT 0,
    [ifonc] int NULL DEFAULT 0,
    [igrad] int NULL,
    [ibank] int NULL DEFAULT 0,
    [icotis] int NULL DEFAULT 0,
    [itax] int NULL DEFAULT 0,
    [ipaid] int NULL DEFAULT 0,
    [ipays] int NULL DEFAULT 0,
    [iregio] int NULL DEFAULT 0,
    [iprovi] int NULL DEFAULT 0,
    [icity] int NULL DEFAULT 0,
    [icomu] int NULL DEFAULT 0,
    [iquarti] int NULL DEFAULT 0,
    [ifami] int NULL DEFAULT 0,
    [idom] int NULL DEFAULT 0,
    [isite] int NULL DEFAULT 0,
    [cdtyp] int NULL DEFAULT 0,
    [cutyp] int NULL DEFAULT 0,
    [colne] int NULL DEFAULT 0,
    [sfonc] nvarchar(150) NULL,
    [sgrad] nvarchar(150) NULL,
    [sbank] nvarchar(150) NULL,
    [scotis] nvarchar(150) NULL,
    [stax] nvarchar(150) NULL,
    [spaid] nvarchar(150) NULL,
    [spays] nvarchar(150) NULL DEFAULT (((0))),
    [sregio] nvarchar(150) NULL,
    [sprovi] nvarchar(150) NULL DEFAULT (((0))),
    [scity] nvarchar(150) NULL,
    [scomu] nvarchar(150) NULL DEFAULT (((0))),
    [squarti] nvarchar(150) NULL,
    [sfami] nvarchar(150) NULL,
    [ttyp] int NULL DEFAULT 0,
    [iloc] int NULL DEFAULT 0,
    [styp] int NULL DEFAULT 0,
    [ordp] int NULL DEFAULT 0,
    [cpgid] int NULL,
    [cpgcod] nvarchar(100) NULL,
    [parqui] int NULL DEFAULT 0,
    [idpere] int NULL DEFAULT 0,
    [idmere] int NULL DEFAULT 0,
    [ifchef] int NULL DEFAULT 0,
    [sno] int NULL DEFAULT 1,
    [psmatri] nvarchar(150) NULL,
    [smatri] nvarchar(150) NULL,
    [xmatri] nvarchar(150) NULL,
    [ymatri] nvarchar(150) NULL,
    [zmatri] nvarchar(250) NULL,
    [intmat] int NULL DEFAULT 0,
    [binid] int NULL DEFAULT 0,
    [siscv] int NULL DEFAULT 0,
    [sioca] int NULL DEFAULT 0,
    [nom] nvarchar(250) NOT NULL,
    [pnom] nvarchar(250) NOT NULL,
    [jpays] int NULL DEFAULT 0,
    [jcity] int NULL DEFAULT 0,
    [kpays] int NULL DEFAULT 0,
    [kcity] int NULL DEFAULT 0,
    [raison] nvarchar(250) NULL,
    [dnais] datetime2(2) NULL,
    [demb] datetime2(2) NULL,
    [dinscr] datetime2(2) NULL,
    [titre] nvarchar(20) NULL,
    [xidtie] nvarchar(80) NULL,
    [nchge] int NULL DEFAULT 0,
    [nenf] int NULL DEFAULT 0,
    [tident] int NULL DEFAULT 0,
    [nident] nvarchar(150) NULL,
    [aident] nvarchar(150) NULL,
    [pident] image NULL,
    [tdiplo] int NULL,
    [ndiplo] nvarchar(150) NULL,
    [adr1] nvarchar(150) NULL,
    [adr2] nvarchar(150) NULL,
    [ivge] int NULL DEFAULT 0,
    [svge] nvarchar(150) NULL,
    [iadr1] int NULL DEFAULT 0,
    [iadr2] int NULL DEFAULT 0,
    [atrplus] xml NULL,
    [nnais] int NULL DEFAULT 0,
    [inais] int NULL DEFAULT 0,
    [iemb] int NULL DEFAULT 0,
    [nactu] int NULL DEFAULT 0,
    [adres1] nvarchar(50) NULL,
    [adres2] nvarchar(50) NULL,
    [inlg] int NULL DEFAULT 0,
    [inth] int NULL DEFAULT 0,
    [idoc] xml NULL,
    [idoca] xml NULL,
    [idocb] xml NULL,
    [photo] image NULL,
    [phot2] image NULL,
    [cdinvite] nvarchar(max) NULL,
    [refa] nvarchar(50) NULL,
    [socacc] nvarchar(200) NULL,
    [idno] nvarchar(50) NULL,
    [id2no] nvarchar(50) NULL,
    [typct] int NULL DEFAULT 0,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [eta] int NULL DEFAULT 0,
    [sia] bit NULL DEFAULT CAST(0 AS bit),
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [datc] datetime2(0) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_tiewel_1] PRIMARY KEY ([idtie])
);
GO

CREATE TABLE [dicpro] (
    [dxseq] int NOT NULL IDENTITY,
    [idorg] int NULL DEFAULT 0,
    [lgseq] int NOT NULL,
    [lgns] nvarchar(10) NULL,
    [dodic] int NULL DEFAULT 0,
    [frodic] int NULL DEFAULT 1,
    [mosq] int NOT NULL,
    [dgvars] int NULL DEFAULT 0,
    [ditb] int NULL DEFAULT 0,
    [delea] int NULL DEFAULT 0,
    [drefa] nvarchar(50) NULL,
    [dliba] nvarchar(100) NULL,
    [dabg] nvarchar(100) NULL,
    [dsliba] nvarchar(150) NULL,
    [dsabg] nvarchar(25) NULL,
    [stdic] int NULL,
    [dlib2] nvarchar(100) NULL,
    [scdrub] nvarchar(50) NULL,
    [fxseq] int NULL,
    [iscre] int NULL DEFAULT 0,
    [gp1] int NULL DEFAULT 0,
    [gp2] int NULL DEFAULT 0,
    [kvars] int NULL,
    [datc] datetime2(2) NULL,
    [eta] int NULL DEFAULT 1,
    [sifx] int NULL DEFAULT 0,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_dicpro] PRIMARY KEY ([dxseq]),
    CONSTRAINT [FK_dicpro_consfix] FOREIGN KEY ([mosq]) REFERENCES [consfix] ([fxseq])
);
GO

CREATE TABLE [gsapl] (
    [idapl] int NOT NULL IDENTITY,
    [apto] int NOT NULL DEFAULT 1,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [idtie] int NULL DEFAULT 0,
    [atyp] int NULL DEFAULT 0,
    [aseq] int NULL DEFAULT 0,
    [refofr] nvarchar(50) NULL,
    [odoca] xml NULL,
    [odocb] xml NULL,
    [sifin] int NULL DEFAULT 0,
    [sirec] int NULL DEFAULT 0,
    [siaco] int NULL DEFAULT 0,
    [siref] int NULL DEFAULT 0,
    [datc] datetime2(2) NULL,
    [datouv] datetime2(2) NULL,
    [datclos] datetime2(2) NULL,
    [datatt] datetime2(2) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_gsapl] PRIMARY KEY ([idapl]),
    CONSTRAINT [FK_gsapl_gxorga] FOREIGN KEY ([idorg]) REFERENCES [gxorga] ([idorg]) ON DELETE CASCADE
);
GO

CREATE TABLE [gsgfix] (
    [xseq] int NOT NULL IDENTITY,
    [tovers] int NULL DEFAULT 1,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [ztyp] int NULL DEFAULT 0,
    [gvars] int NOT NULL,
    [itb] int NOT NULL,
    [elea] int NOT NULL,
    [liba] nvarchar(150) NULL,
    [sliba] nvarchar(150) NULL,
    [abg] nvarchar(25) NULL,
    [sabg] nvarchar(25) NULL,
    [refa] nvarchar(25) NULL,
    [totyp] int NULL DEFAULT 0,
    [t2typ] int NULL DEFAULT 0,
    [t3typ] int NULL DEFAULT 0,
    [etyp] int NULL DEFAULT 0,
    [emdl] int NULL DEFAULT 0,
    [epai] int NULL DEFAULT 1,
    [gtyp] int NULL DEFAULT 0,
    [dpdce] int NULL DEFAULT 0,
    [tdpd] nchar(10) NULL,
    [xdpd] int NULL DEFAULT 0,
    [ydpd] int NULL DEFAULT 0,
    [dptb] int NULL DEFAULT 0,
    [zfro] int NULL DEFAULT 0,
    [zgpe] int NULL DEFAULT 0,
    [gat] int NULL DEFAULT 2,
    [idpln] int NULL DEFAULT 0,
    [idpgr] int NULL DEFAULT 0,
    [iperi] int NULL,
    [pseq] int NULL DEFAULT 0,
    [xsac] int NULL DEFAULT 0,
    [psac] int NULL DEFAULT 0,
    [scdrub] nvarchar(50) NULL,
    [icdrub] int NULL,
    [jtyp] int NULL DEFAULT 0,
    [pgnom] nvarchar(50) NULL,
    [clnom] nvarchar(50) NULL,
    [varbloc] nvarchar(max) NULL,
    [princbloc] nvarchar(max) NULL,
    [procbloc] nvarchar(max) NULL,
    [fpsource] nvarchar(max) NULL,
    [fpcpl] nvarchar(max) NULL,
    [fpexec] nvarchar(max) NULL,
    [xuid] nvarchar(450) NULL,
    [xumail] nvarchar(256) NULL,
    [xuphone] nvarchar(max) NULL,
    [xunom] nvarchar(150) NULL,
    [xupnom] nvarchar(250) NULL,
    [xuraison] nvarchar(max) NULL,
    [sitie] bit NULL DEFAULT CAST(0 AS bit),
    [xlrubs] xml NULL,
    [xlprubs] xml NULL,
    [xlplus] xml NULL,
    [hrtyp] int NULL DEFAULT 0,
    [serrors] nvarchar(max) NULL,
    [verrors] nvarchar(max) NULL,
    [perrors] nvarchar(max) NULL,
    [sicpl] int NULL DEFAULT 0,
    [siexc] int NULL DEFAULT 0,
    [sidecl] bit NULL DEFAULT CAST(0 AS bit),
    [sifunc] bit NULL DEFAULT CAST(0 AS bit),
    [siprog] bit NULL DEFAULT CAST(0 AS bit),
    [siest] int NULL DEFAULT 0,
    [sigrid] int NULL DEFAULT 0,
    [svala] nvarchar(50) NULL,
    [sval2] nvarchar(50) NULL,
    [siti2] bit NULL DEFAULT CAST(0 AS bit),
    [iorig] int NULL DEFAULT 0,
    [iori2] int NULL DEFAULT 0,
    [ivala] int NULL DEFAULT 0,
    [ival2] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [rval2] real NULL DEFAULT CAST(0 AS real),
    [dval] datetime2(2) NULL,
    [fval] datetime2(2) NULL,
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [bval2] bit NULL DEFAULT CAST(0 AS bit),
    [speri] nvarchar(20) NULL,
    [sdouv] nvarchar(20) NULL,
    [sdclot] nvarchar(20) NULL,
    [douv] datetime2(2) NULL,
    [dclot] datetime2(2) NULL,
    [didtie] int NULL DEFAULT 0,
    [fidtie] int NULL DEFAULT 0,
    [siclot] bit NULL,
    [siouv] bit NULL,
    [tous] bit NULL DEFAULT CAST(1 AS bit),
    [ede] int NULL,
    [ade] int NULL,
    [eseq] int NULL DEFAULT 0,
    [sval3] nvarchar(50) NULL,
    [lgt1] int NULL DEFAULT 0,
    [lgft] nvarchar(50) NULL,
    [lgt2] int NULL DEFAULT 0,
    [ft1] nvarchar(150) NULL,
    [ft2] nvarchar(150) NULL,
    [ftl1] nvarchar(50) NULL,
    [ftl2] nvarchar(50) NULL,
    [datc] datetime2(2) NULL,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(1 AS bit),
    [eta] int NULL DEFAULT 0,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_gsgfix] PRIMARY KEY ([xseq]),
    CONSTRAINT [FK_gsgfix_gxorga] FOREIGN KEY ([idorg]) REFERENCES [gxorga] ([idorg])
);
GO

CREATE TABLE [ojgen] (
    [idig] int NOT NULL IDENTITY,
    [jtyp] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [dope] datetime2 NULL DEFAULT ((getdate())),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_ojgen] PRIMARY KEY ([idig]),
    CONSTRAINT [FK_ojgen_gxorga] FOREIGN KEY ([idorg]) REFERENCES [gxorga] ([idorg])
);
GO

CREATE TABLE [plngen] (
    [idpln] int NOT NULL IDENTITY,
    [elea] int NULL,
    [refa] nvarchar(25) NULL,
    [tovers] int NULL DEFAULT 1,
    [idorg] int NOT NULL,
    [idhie] int NULL DEFAULT 0,
    [idcent] int NULL DEFAULT 0,
    [ptyp] int NULL DEFAULT 0,
    [totyp] int NULL DEFAULT 1,
    [tycbl] int NULL DEFAULT 1,
    [tocod] int NULL,
    [styp] int NULL DEFAULT 0,
    [irecap] int NULL DEFAULT 0,
    [tcalc] int NULL DEFAULT 1,
    [tostyp] int NULL DEFAULT 1,
    [to2typ] int NULL DEFAULT 1,
    [totie] int NULL DEFAULT 0,
    [liba] nvarchar(250) NOT NULL,
    [abg] nvarchar(50) NULL,
    [plgstat] nvarchar(200) NULL,
    [ftperi] nvarchar(15) NULL,
    [gptyp] int NULL DEFAULT 0,
    [fpsource] nvarchar(max) NULL,
    [f2source] nvarchar(max) NULL,
    [plsact] int NULL DEFAULT 0,
    [plspro] int NULL DEFAULT 0,
    [plsgri] int NULL DEFAULT 0,
    [plssit] int NULL DEFAULT 0,
    [plsgeo] int NULL DEFAULT 0,
    [plscum] int NULL DEFAULT 0,
    [plscpt] int NULL DEFAULT 0,
    [plspgr] int NULL DEFAULT 0,
    [plsdiv] int NULL DEFAULT 0,
    [plstie] int NULL DEFAULT 0,
    [fpexec] nvarchar(max) NULL,
    [pnom] nvarchar(200) NULL,
    [sicpl] int NULL DEFAULT 0,
    [siexc] int NULL DEFAULT 0,
    [topln] int NULL DEFAULT 0,
    [percal] int NULL DEFAULT 2,
    [strplus] xml NULL,
    [eta] int NULL DEFAULT 0,
    [cod2] nvarchar(50) NULL,
    [atyp] int NULL DEFAULT 0,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [lib2] nvarchar(150) NULL,
    [strb] nvarchar(250) NULL,
    [sifo] bit NULL DEFAULT CAST(0 AS bit),
    [sia] bit NULL DEFAULT CAST(0 AS bit),
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_plngen] PRIMARY KEY ([idpln]),
    CONSTRAINT [FK_plngen_gxorga] FOREIGN KEY ([idorg]) REFERENCES [gxorga] ([idorg])
);
GO

CREATE TABLE [skprod] (
    [idpdt] int NOT NULL IDENTITY,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL,
    [idpst] int NULL DEFAULT 0,
    [xtyp] int NULL DEFAULT 0,
    [sno] int NULL DEFAULT 0,
    [idhfa] int NULL,
    [kemb] int NULL DEFAULT 0,
    [kprix] decimal(18,0) NULL,
    [mprix] decimal(18,0) NULL,
    [kreb] int NULL DEFAULT 0,
    [kqte] int NULL DEFAULT 0,
    [kinit] int NULL DEFAULT 0,
    [kalert] int NULL DEFAULT 0,
    [kdent] int NULL DEFAULT 0,
    [kdreb] int NULL DEFAULT 0,
    [totyp] int NOT NULL DEFAULT 1,
    [htyp] int NULL,
    [uraz] int NULL DEFAULT 0,
    [categ] int NULL DEFAULT 0,
    [fami] int NULL,
    [sitmat] int NULL DEFAULT 0,
    [condit] int NULL DEFAULT 0,
    [couleur] int NULL DEFAULT 0,
    [ipaid] int NULL DEFAULT 0,
    [ipays] int NULL DEFAULT 0,
    [iloc] int NULL DEFAULT 0,
    [styp] int NULL DEFAULT 0,
    [idpere] int NULL DEFAULT 0,
    [idmere] int NULL DEFAULT 0,
    [sichef] int NULL DEFAULT 0,
    [dfab] datetime2(2) NULL,
    [dper] datetime2(2) NULL,
    [dfint] int NULL DEFAULT 0,
    [dpint] int NULL DEFAULT 0,
    [d2fab] datetime2(2) NULL,
    [d2per] datetime2(2) NULL,
    [idoca] nvarchar(max) NULL,
    [photo] nvarchar(max) NULL,
    [phot2] image NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_skprod] PRIMARY KEY ([idpdt]),
    CONSTRAINT [FK_skprod_gxorga] FOREIGN KEY ([idorg]) REFERENCES [gxorga] ([idorg]) ON DELETE CASCADE
);
GO

CREATE TABLE [tiersp] (
    [idtie] int NOT NULL IDENTITY,
    [usrid] nvarchar(450) NULL,
    [usrname] nvarchar(256) NULL,
    [usremail] nvarchar(max) NULL,
    [usrphone] nvarchar(500) NULL,
    [siset] int NULL DEFAULT 0,
    [usrsocial] nvarchar(400) NULL,
    [sigrid] int NULL DEFAULT 0,
    [weltie] int NULL DEFAULT 0,
    [natio] int NULL DEFAULT 0,
    [resid] int NULL,
    [tymut] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL,
    [idpst] int NULL DEFAULT 0,
    [idgeo] int NULL DEFAULT 0,
    [statut] int NULL DEFAULT 0,
    [sexe] int NULL,
    [sitmat] int NULL DEFAULT 0,
    [ifonc] int NULL DEFAULT 0,
    [igrad] int NULL,
    [ibank] int NULL DEFAULT 0,
    [icotis] int NULL DEFAULT 0,
    [itax] int NULL DEFAULT 0,
    [ipaid] int NULL DEFAULT 0,
    [ipays] int NULL DEFAULT 0,
    [iregio] int NULL DEFAULT 0,
    [iprovi] int NULL DEFAULT 0,
    [icity] int NULL DEFAULT 0,
    [icomu] int NULL DEFAULT 0,
    [iquarti] int NULL DEFAULT 0,
    [ifami] int NULL DEFAULT 0,
    [shie] nvarchar(200) NULL,
    [sfonc] nvarchar(150) NULL,
    [sgrad] nvarchar(150) NULL,
    [sbank] nvarchar(150) NULL,
    [scotis] nvarchar(150) NULL,
    [stax] nvarchar(150) NULL,
    [spaid] nvarchar(150) NULL,
    [spays] nvarchar(150) NULL DEFAULT (((0))),
    [sregio] nvarchar(150) NULL,
    [sprovi] nvarchar(150) NULL DEFAULT (((0))),
    [scity] nvarchar(150) NULL,
    [scomu] nvarchar(150) NULL DEFAULT (((0))),
    [squarti] nvarchar(150) NULL,
    [sfami] nvarchar(150) NULL,
    [ttyp] int NULL DEFAULT 0,
    [iloc] int NULL DEFAULT 0,
    [styp] int NULL DEFAULT 0,
    [ordp] int NULL DEFAULT 0,
    [idpere] int NULL DEFAULT 0,
    [idmere] int NULL DEFAULT 0,
    [sichef] int NULL DEFAULT 0,
    [sno] int NULL DEFAULT 1,
    [psmatri] nvarchar(150) NULL,
    [smatri] nvarchar(150) NULL,
    [xmatri] nvarchar(150) NULL,
    [ymatri] nvarchar(150) NULL,
    [zmatri] nvarchar(250) NULL,
    [intmat] int NULL DEFAULT 0,
    [binid] int NULL DEFAULT 0,
    [siscv] int NULL DEFAULT 0,
    [sioca] int NULL DEFAULT 0,
    [nom] nvarchar(250) NOT NULL,
    [pnom] nvarchar(250) NOT NULL,
    [jpays] int NULL DEFAULT 0,
    [jcity] int NULL DEFAULT 0,
    [kpays] int NULL DEFAULT 0,
    [kcity] int NULL DEFAULT 0,
    [raison] nvarchar(250) NULL,
    [dnais] datetime2(2) NULL,
    [demb] datetime2(2) NULL,
    [dinscr] datetime2(2) NULL,
    [titre] nvarchar(20) NULL,
    [xidtie] nvarchar(80) NULL,
    [nchge] int NULL DEFAULT 0,
    [nenf] int NULL DEFAULT 0,
    [tident] int NULL DEFAULT 0,
    [nident] nvarchar(150) NULL,
    [aident] nvarchar(150) NULL,
    [pident] image NULL,
    [tdiplo] int NULL,
    [ndiplo] nvarchar(150) NULL,
    [adr1] nvarchar(150) NULL,
    [adr2] nvarchar(150) NULL,
    [ivge] int NULL DEFAULT 0,
    [svge] nvarchar(150) NULL,
    [iadr1] int NULL DEFAULT 0,
    [iadr2] int NULL DEFAULT 0,
    [atrplus] xml NULL,
    [nnais] int NULL DEFAULT 0,
    [inais] int NULL DEFAULT 0,
    [iemb] int NULL DEFAULT 0,
    [nactu] int NULL DEFAULT 0,
    [adres1] nvarchar(50) NULL,
    [adres2] nvarchar(50) NULL,
    [inlg] int NULL DEFAULT 0,
    [inth] int NULL DEFAULT 0,
    [idoc] xml NULL,
    [idoca] xml NULL,
    [idocb] xml NULL,
    [photo] image NULL,
    [phot2] image NULL,
    [refa] nvarchar(50) NULL,
    [socacc] nvarchar(200) NULL,
    [idno] nvarchar(50) NULL,
    [id2no] nvarchar(50) NULL,
    [typct] int NULL DEFAULT 0,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [eta] int NULL DEFAULT 0,
    [sia] bit NULL DEFAULT CAST(0 AS bit),
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [datc] datetime2(0) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_tiersp] PRIMARY KEY ([idtie]),
    CONSTRAINT [FK_tiersp_gxorga] FOREIGN KEY ([idorg]) REFERENCES [gxorga] ([idorg])
);
GO

CREATE TABLE [ocmde] (
    [cdeid] int NOT NULL IDENTITY,
    [vutyp] int NOT NULL,
    [cdtyp] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [cdlne] int NULL DEFAULT 0,
    [c2lne] int NULL DEFAULT 0,
    [usrid] nvarchar(450) NULL,
    [cdusrid] nvarchar(450) NULL,
    [dom] int NULL DEFAULT 0,
    [site] int NULL DEFAULT 0,
    [stdom] nvarchar(300) NULL,
    [stsite] nvarchar(300) NULL,
    [stsigle] nvarchar(200) NULL,
    [siowner] bit NULL DEFAULT CAST(0 AS bit),
    [colne] int NULL DEFAULT 0,
    [cutyp] int NULL DEFAULT 0,
    [idtie] int NULL DEFAULT 0,
    [idtiw] int NULL DEFAULT 0,
    [sisetup] int NULL DEFAULT 0,
    [ipays] int NULL DEFAULT 0,
    [spays] nvarchar(150) NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_ocmde] PRIMARY KEY ([cdeid]),
    CONSTRAINT [FK_ocmde_tiewel] FOREIGN KEY ([idtiw]) REFERENCES [tiewel] ([idtie])
);
GO

CREATE TABLE [tiwatr] (
    [idtie] int NOT NULL,
    [noatr] int NOT NULL,
    [atseq] int NULL DEFAULT 0,
    [zcdati] nvarchar(50) NULL,
    [siat] int NULL DEFAULT 0,
    [adpd] int NULL DEFAULT 0,
    [xdpd] int NULL DEFAULT 0,
    [ydpd] int NULL DEFAULT 0,
    [dpdsac] int NULL DEFAULT 0,
    [pnoatr] nvarchar(50) NULL DEFAULT (((0))),
    [atyp] int NULL DEFAULT 1,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [totyp] int NULL DEFAULT 1,
    [htyp] int NULL,
    [uraz] int NULL DEFAULT 0,
    [gxseq] int NULL DEFAULT 0,
    [idoc] nvarchar(max) NULL,
    [idoca] nvarchar(max) NULL,
    [idocb] nvarchar(max) NULL,
    [photo] nvarchar(max) NULL,
    [phot2] image NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [eta] int NULL DEFAULT 0,
    [selc] bit NULL DEFAULT CAST(1 AS bit),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_tiwatr_1] PRIMARY KEY ([idtie], [noatr]),
    CONSTRAINT [FK_tiwatr_tiewel] FOREIGN KEY ([idtie]) REFERENCES [tiewel] ([idtie])
);
GO

CREATE TABLE [ojusr] (
    [idjg] int NOT NULL,
    [idju] int NOT NULL,
    [uname] nvarchar(250) NULL,
    [usid] nvarchar(450) NULL,
    [ojgpe] int NULL DEFAULT 0,
    [ojrole] int NULL DEFAULT 0,
    [omenu] int NULL DEFAULT 0,
    [tachid] int NULL DEFAULT 0,
    [tachs] nvarchar(200) NULL,
    [tachp] image NULL,
    [ddep] datetime2(0) NULL,
    [dfin] datetime2(0) NULL,
    [dope] datetime2 NULL DEFAULT ((getdate())),
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(50) NULL,
    CONSTRAINT [PK_ojusr] PRIMARY KEY ([idjg], [idju]),
    CONSTRAINT [FK_ojusr_ojgen] FOREIGN KEY ([idjg]) REFERENCES [ojgen] ([idig])
);
GO

CREATE TABLE [gsessu] (
    [idses] int NOT NULL IDENTITY,
    [idpln] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [tses] int NULL DEFAULT 0,
    [speri] nvarchar(8) NULL DEFAULT (((0))),
    [xsac] int NULL DEFAULT 0,
    [susr] int NULL DEFAULT 0,
    [nivo] int NULL DEFAULT 0,
    [tperi] int NULL,
    [sdeb] nvarchar(15) NULL,
    [sfin] nvarchar(15) NULL,
    [ideb] int NULL DEFAULT 0,
    [ifin] int NULL,
    [idrub] int NULL DEFAULT 0,
    [sicur] int NULL DEFAULT 0,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [usrsup] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(200) NULL,
    CONSTRAINT [PK_gsescu] PRIMARY KEY ([idses]),
    CONSTRAINT [FK_gsessu_plngen] FOREIGN KEY ([idpln]) REFERENCES [plngen] ([idpln])
);
GO

CREATE TABLE [gshier] (
    [idhie] int NOT NULL IDENTITY,
    [idpln] int NULL,
    [idorg] int NOT NULL,
    [elea] int NULL DEFAULT 0,
    [tyhie] int NULL DEFAULT 0,
    [tyreel] int NULL,
    [raison] nvarchar(450) NOT NULL,
    [sigle] nvarchar(150) NULL,
    [liba] nvarchar(150) NULL,
    [abg] nvarchar(50) NULL,
    [hdpd] int NULL DEFAULT 0,
    [udpd] int NULL DEFAULT 0,
    [kdgd] int NULL DEFAULT 0,
    [xdpd] int NULL DEFAULT 0,
    [ydpd] int NULL DEFAULT 0,
    [lbcbl] nvarchar(50) NULL DEFAULT (((0))),
    [slbcbl] nvarchar(50) NULL DEFAULT (((0))),
    [smatri] nvarchar(150) NULL,
    [siafil] int NULL DEFAULT 0,
    [siagt] int NULL DEFAULT 0,
    [siope] int NULL DEFAULT 0,
    [siclie] int NULL DEFAULT 0,
    [sifour] int NULL DEFAULT 0,
    [sidic] int NULL DEFAULT 1,
    [tylib] int NULL DEFAULT 0,
    [refa] nvarchar(25) NULL,
    [udpd2] int NULL DEFAULT 0,
    [xdpd2] int NULL DEFAULT 0,
    [ydpd2] int NULL DEFAULT 0,
    [liba2] nvarchar(150) NULL,
    [abg2] nvarchar(25) NULL,
    [scdrub] nvarchar(50) NOT NULL,
    [rtyp] int NULL DEFAULT 1,
    [torub] int NULL DEFAULT 0,
    [eidrub] int NULL,
    [didpln] int NULL,
    [didrub] int NULL,
    [tcalc] int NULL DEFAULT 0,
    [utyp] int NULL DEFAULT 0,
    [ustyp] int NULL DEFAULT 0,
    [lgcdrub] nvarchar(50) NULL,
    [hlevel] AS ([nivhie].[GetLevel]()),
    [nivlne] int NULL DEFAULT 0,
    [nivcol] int NULL DEFAULT 0,
    [uraz] int NULL DEFAULT 0,
    [tosrub] int NULL DEFAULT 0,
    [pidpln] int NULL,
    [pidrub] int NULL,
    [pptyp] int NULL,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(0) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [divala] int NULL,
    [sifin] int NULL DEFAULT 0,
    [sifor] int NULL DEFAULT 0,
    [sicmp] int NULL DEFAULT 0,
    [icdrub] int NULL DEFAULT 0,
    [operi] int NULL DEFAULT 0,
    [stdstr] nvarchar(30) NULL,
    [stfstr] nvarchar(50) NULL,
    [tperi] int NULL DEFAULT 1,
    [ddval] int NULL DEFAULT 0,
    [dfval] int NULL DEFAULT 0,
    [lib2] nvarchar(50) NULL,
    [frsource] nvarchar(max) NULL,
    [rcm] nvarchar(250) NULL,
    [rifu] nvarchar(250) NULL,
    [ircm] int NULL DEFAULT 0,
    [irfu] int NULL DEFAULT 0,
    [adr] nvarchar(max) NULL,
    [adr2] nvarchar(max) NULL,
    [codi] int NULL DEFAULT 0,
    [cods] nvarchar(100) NULL,
    [natio] int NULL DEFAULT 0,
    [resid] int NULL DEFAULT 0,
    [ibank] int NULL DEFAULT 0,
    [icotis] int NULL DEFAULT 0,
    [itax] int NULL DEFAULT 0,
    [ipaid] int NULL DEFAULT 0,
    [ipays] int NULL DEFAULT 0,
    [iregio] int NULL DEFAULT 0,
    [iprovi] int NULL DEFAULT 0,
    [icity] int NULL DEFAULT 0,
    [icomu] int NULL DEFAULT 0,
    [iquarti] int NULL DEFAULT 0,
    [sbank] nvarchar(150) NULL,
    [scotis] nvarchar(150) NULL,
    [stax] nvarchar(150) NULL,
    [spaid] nvarchar(150) NULL,
    [spays] nvarchar(150) NULL DEFAULT (((0))),
    [sregio] nvarchar(150) NULL,
    [sprovi] nvarchar(150) NULL DEFAULT (((0))),
    [scity] nvarchar(150) NULL,
    [scomu] nvarchar(150) NULL DEFAULT (((0))),
    [squarti] nvarchar(150) NULL,
    [jcity] int NULL DEFAULT 0,
    [photo] nvarchar(max) NULL,
    [photo2] image NULL,
    [photo3] nvarchar(max) NULL,
    [idoca] nvarchar(max) NULL,
    [idocb] nvarchar(max) NULL,
    [idoce] nvarchar(max) NULL,
    [tele] nvarchar(100) NULL,
    [tele2] nvarchar(100) NULL,
    [whatsapp] nvarchar(100) NULL,
    [email] nvarchar(200) NULL,
    [phone] nvarchar(150) NULL,
    [siteweb] nvarchar(200) NULL,
    [rnom] nvarchar(250) NULL,
    [rpnom] nvarchar(250) NULL,
    [cnom] nvarchar(250) NULL,
    [cpnom] nvarchar(250) NULL,
    [cip] nvarchar(200) NULL,
    [devise] nvarchar(20) NULL,
    [stdevi] nvarchar(20) NULL,
    [spdevi] nvarchar(20) NULL,
    [mdevi] nvarchar(20) NULL,
    [ddeci] int NULL DEFAULT 0,
    [nxplan] int NULL DEFAULT 0,
    [depdat] datetime2(0) NULL,
    [depstr] nvarchar(25) NULL,
    [depexy] int NULL,
    [depexm] int NULL,
    [depexd] int NULL,
    [prvdat] datetime2(0) NULL,
    [prvstr] nvarchar(25) NULL,
    [prvexy] int NULL,
    [prvexm] int NULL,
    [prvexd] int NULL,
    [findat] datetime2(0) NULL,
    [finstr] nvarchar(25) NULL,
    [finexy] int NULL,
    [finexm] int NULL,
    [finexd] int NULL,
    [eta] int NULL DEFAULT 1,
    [selc] bit NOT NULL,
    [datc] datetime2(0) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_gshier] PRIMARY KEY ([idhie]),
    CONSTRAINT [FK_gshier_plngen] FOREIGN KEY ([idpln]) REFERENCES [plngen] ([idpln])
);
GO

CREATE TABLE [rubvar] (
    [idrub] int NOT NULL IDENTITY,
    [refa] nvarchar(25) NULL,
    [idpln] int NOT NULL,
    [scdrub] nvarchar(50) NOT NULL,
    [rtyp] int NULL DEFAULT 1,
    [torub] int NULL DEFAULT 0,
    [udpd] int NULL DEFAULT 0,
    [xdpd] int NULL DEFAULT 0,
    [ydpd] int NULL DEFAULT 0,
    [eidrub] int NULL,
    [didpln] int NULL,
    [didrub] int NULL,
    [tcalc] int NULL DEFAULT 0,
    [liba] nvarchar(150) NULL,
    [abg] nvarchar(25) NULL,
    [utyp] int NULL DEFAULT 0,
    [ustyp] int NULL DEFAULT 0,
    [lgcdrub] nvarchar(50) NULL,
    [uraz] int NULL DEFAULT 0,
    [tosrub] int NULL DEFAULT 0,
    [dpdce] int NULL,
    [pptyp] int NULL,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(0) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [divala] int NULL,
    [eint] int NULL DEFAULT 0,
    [e2int] int NULL DEFAULT 0,
    [emont] decimal(18,4) NULL DEFAULT 0.0,
    [e2mont] decimal(18,4) NULL DEFAULT 0.0,
    [sifin] int NULL DEFAULT 0,
    [sifor] int NULL DEFAULT 0,
    [sicmp] int NULL DEFAULT 0,
    [icdrub] int NULL DEFAULT 0,
    [operi] int NULL DEFAULT 0,
    [stdstr] nvarchar(30) NULL,
    [stfstr] nvarchar(50) NULL,
    [tperi] int NULL DEFAULT 1,
    [ddval] int NULL DEFAULT 0,
    [dfval] int NULL DEFAULT 0,
    [lib2] nvarchar(50) NULL,
    [frsource] nvarchar(max) NULL,
    [f2source] nvarchar(max) NULL,
    [f3source] nvarchar(max) NULL,
    [frbinaire] nvarchar(max) NULL,
    [col] int NULL,
    [lne] int NULL,
    [ftout] nvarchar(80) NULL,
    [rpre] nvarchar(10) NULL,
    [torig] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [tdeft] int NULL DEFAULT 0,
    [tvers] int NULL DEFAULT 0,
    [gdact] int NULL DEFAULT 0,
    [ugpe] int NULL DEFAULT 0,
    [lgt1] int NULL DEFAULT 0,
    [lgft] nvarchar(50) NULL,
    [strb] nvarchar(250) NULL,
    [eta] int NULL DEFAULT 0,
    [siobl] bit NULL DEFAULT CAST(0 AS bit),
    [tsize] int NULL DEFAULT 0,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(1 AS bit),
    [datc] datetime2(0) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_rubvar] PRIMARY KEY ([idrub]),
    CONSTRAINT [FK_rubvar_plngen] FOREIGN KEY ([idpln]) REFERENCES [plngen] ([idpln])
);
GO

CREATE TABLE [skpatr] (
    [idpdt] int NOT NULL,
    [noatr] int NOT NULL,
    [atseq] int NULL DEFAULT 0,
    [zcdati] nvarchar(50) NULL,
    [siat] int NULL DEFAULT 0,
    [adpd] int NULL DEFAULT 0,
    [xdpd] int NULL DEFAULT 0,
    [ydpd] int NULL DEFAULT 0,
    [dpdsac] int NULL DEFAULT 0,
    [pnoatr] nvarchar(50) NULL DEFAULT (((0))),
    [atyp] int NULL DEFAULT 1,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [totyp] int NULL DEFAULT 1,
    [htyp] int NULL,
    [uraz] int NULL DEFAULT 0,
    [gxseq] int NULL DEFAULT 0,
    [idoc] nvarchar(max) NULL,
    [idoca] nvarchar(max) NULL,
    [idocb] nvarchar(max) NULL,
    [photo] nvarchar(max) NULL,
    [phot2] image NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [eta] int NULL DEFAULT 0,
    [selc] bit NULL DEFAULT CAST(1 AS bit),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_skpatr_1] PRIMARY KEY ([idpdt], [noatr]),
    CONSTRAINT [FK_skpatr_skprod] FOREIGN KEY ([idpdt]) REFERENCES [skprod] ([idpdt])
);
GO

CREATE TABLE [resdon] (
    [idres] int NOT NULL IDENTITY,
    [operi] int NOT NULL,
    [idtie] int NOT NULL,
    [ucdres] nvarchar(100) NOT NULL,
    [nopai] int NOT NULL,
    [matri] nvarchar(50) NULL,
    [typln] int NULL DEFAULT 0,
    [idrub] int NULL DEFAULT 0,
    [idzon] int NULL DEFAULT 0,
    [idact] int NULL DEFAULT 0,
    [ordac] int NULL DEFAULT 0,
    [rcdrub] nvarchar(50) NULL,
    [zcdrub] nvarchar(50) NULL DEFAULT (((0))),
    [utyp] int NULL DEFAULT 0,
    [plngri] int NULL DEFAULT 0,
    [plnpln] int NULL DEFAULT 0,
    [plnpgr] int NULL DEFAULT 0,
    [plnrub] int NULL DEFAULT 0,
    [pgrrub] int NULL DEFAULT 0,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] decimal(18,3) NULL DEFAULT 0.0,
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [tperi] int NULL DEFAULT 1,
    [kcqte] int NULL DEFAULT 0,
    [kcprix] decimal(18,4) NULL DEFAULT 0.0,
    [kcvala] decimal(18,4) NULL DEFAULT 0.0,
    [rsens] int NULL DEFAULT 0,
    [vhtx] decimal(18,4) NULL DEFAULT 0.0,
    [vtax] decimal(18,4) NULL DEFAULT 0.0,
    [vtva] decimal(18,4) NULL DEFAULT 0.0,
    [vred] decimal(18,4) NULL DEFAULT 0.0,
    [vdiv] decimal(18,4) NULL DEFAULT 0.0,
    [vtht] decimal(18,4) NULL DEFAULT 0.0,
    [vttc] decimal(18,4) NULL DEFAULT 0.0,
    [vnet] decimal(18,4) NULL DEFAULT 0.0,
    [indat] int NULL DEFAULT 0,
    [strdiv] nvarchar(100) NULL,
    [evala] decimal(18,4) NULL DEFAULT 0.0,
    [fvala] float NULL DEFAULT 0.0E0,
    [ecpris] int NULL DEFAULT 0,
    [ecoac] int NULL DEFAULT 0,
    [rorig] int NULL DEFAULT 1,
    [ridzon] int NULL DEFAULT 0,
    [cpre] nvarchar(5) NULL,
    [typb] int NULL DEFAULT 0,
    [strmx] nvarchar(max) NULL,
    [froac] int NULL DEFAULT 0,
    [rmatri] nvarchar(50) NOT NULL,
    [sidet] int NULL DEFAULT 0,
    [ridsuc] int NOT NULL,
    [strb] nvarchar(250) NULL,
    [jour] int NULL DEFAULT 0,
    [mois] int NULL DEFAULT 0,
    [an] int NULL DEFAULT 0,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [eta] int NULL DEFAULT 0,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [usrmin] nvarchar(450) NULL,
    [usris2] nvarchar(450) NULL,
    [udmin] datetime2(0) NULL,
    [udis2] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_resdon] PRIMARY KEY ([idres]),
    CONSTRAINT [FK_resdon_tiersp] FOREIGN KEY ([idtie]) REFERENCES [tiersp] ([idtie])
);
GO

CREATE TABLE [tieafil] (
    [idafil] int NOT NULL IDENTITY,
    [tyafil] int NULL DEFAULT 0,
    [idtie] int NULL,
    [idfam] int NULL DEFAULT 0,
    [idchef] int NULL DEFAULT 0,
    [xnom] nvarchar(250) NULL,
    [xpnom] nvarchar(250) NULL,
    [xnais] int NULL,
    [xeta] int NULL DEFAULT 0,
    [scdfil] nvarchar(50) NULL,
    [tlink] int NULL DEFAULT 0,
    [sqlnk] int NULL DEFAULT 0,
    [sichef] int NULL DEFAULT 0,
    [iotyp] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [liba] nvarchar(200) NULL,
    [abg] nvarchar(50) NULL,
    [refa] nvarchar(80) NULL,
    [kidtie] int NULL DEFAULT 0,
    [mtno] nvarchar(80) NULL,
    [locmut] int NULL,
    [slocmut] nvarchar(250) NULL,
    [fdoc] nvarchar(max) NULL,
    [fdocb] nvarchar(max) NULL,
    [tperi] int NULL DEFAULT 0,
    [operi] int NULL DEFAULT 0,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [mtyp] int NULL,
    [mseq] int NULL,
    [codb] nvarchar(80) NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [eta] int NULL DEFAULT 0,
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [ela] int NULL,
    [emont] decimal(18,3) NULL DEFAULT 0.0,
    [esolde] decimal(18,3) NULL DEFAULT 0.0,
    [ecredi] decimal(18,3) NULL DEFAULT 0.0,
    [edebi] decimal(18,3) NULL DEFAULT 0.0,
    [st1] nvarchar(150) NULL,
    [id1] datetime2(2) NULL,
    [datope] datetime2(0) NULL,
    [datupd] datetime2 NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_tieafil] PRIMARY KEY ([idafil]),
    CONSTRAINT [FK_tieafil_tiersp] FOREIGN KEY ([idtie]) REFERENCES [tiersp] ([idtie])
);
GO

CREATE TABLE [tieapl] (
    [idapl] int NOT NULL IDENTITY,
    [idtie] int NULL,
    [atyp] int NULL DEFAULT 1,
    [idofr] int NULL,
    [apto] int NULL DEFAULT 1,
    [aseq] int NULL DEFAULT 0,
    [refofr] nvarchar(50) NULL,
    [odoca] xml NULL,
    [odocb] xml NULL,
    [sifin] int NULL DEFAULT 0,
    [sirec] int NULL DEFAULT 0,
    [siaco] int NULL DEFAULT 0,
    [siref] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL,
    [datouv] datetime2(2) NULL,
    [datclos] datetime2(2) NULL,
    [datatt] datetime2(2) NULL,
    [datc] datetime2(2) NULL,
    [eta] int NULL DEFAULT 0,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    CONSTRAINT [PK_tieapl] PRIMARY KEY ([idapl]),
    CONSTRAINT [FK_tieapl_tiersp] FOREIGN KEY ([idtie]) REFERENCES [tiersp] ([idtie])
);
GO

CREATE TABLE [tieatr] (
    [idtie] int NOT NULL,
    [noatr] int NOT NULL,
    [atseq] int NULL DEFAULT 0,
    [zcdati] nvarchar(50) NULL,
    [siat] int NULL DEFAULT 0,
    [adpd] int NULL DEFAULT 0,
    [xdpd] int NULL DEFAULT 0,
    [ydpd] int NULL DEFAULT 0,
    [dpdsac] int NULL DEFAULT 0,
    [pnoatr] nvarchar(50) NULL DEFAULT (((0))),
    [atyp] int NULL DEFAULT 1,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [totyp] int NULL DEFAULT 1,
    [htyp] int NULL,
    [uraz] int NULL DEFAULT 0,
    [gxseq] int NULL DEFAULT 0,
    [idoc] nvarchar(max) NULL,
    [idoca] nvarchar(max) NULL,
    [idocb] nvarchar(max) NULL,
    [photo] nvarchar(max) NULL,
    [phot2] image NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [eta] int NULL DEFAULT 0,
    [selc] bit NULL DEFAULT CAST(1 AS bit),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_tieatr] PRIMARY KEY ([idtie], [noatr]),
    CONSTRAINT [FK_tieatr_tiersp] FOREIGN KEY ([idtie]) REFERENCES [tiersp] ([idtie])
);
GO

CREATE TABLE [tiecpt] (
    [idcpt] int NOT NULL IDENTITY,
    [idrub] int NULL,
    [nostr] nvarchar(50) NULL,
    [sctrub] nvarchar(150) NULL,
    [operi] int NULL DEFAULT 0,
    [opdat] datetime2(2) NULL,
    [idtie] int NULL,
    [debit] decimal(18,0) NULL,
    [credit] decimal(18,0) NULL,
    [solde] decimal(18,0) NULL,
    [attend] decimal(18,0) NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [sict] bit NULL DEFAULT CAST(0 AS bit),
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_tiecpt] PRIMARY KEY ([idcpt]),
    CONSTRAINT [FK_tiecpt_tiersp] FOREIGN KEY ([idtie]) REFERENCES [tiersp] ([idtie])
);
GO

CREATE TABLE [tiecum] (
    [idcum] int NOT NULL IDENTITY,
    [operi] int NULL DEFAULT 0,
    [otyp] int NULL,
    [nostr] nvarchar(50) NULL,
    [pidpln] int NULL,
    [idrub] int NULL,
    [ucdcu] nvarchar(50) NULL,
    [uante] real NULL DEFAULT CAST(0 AS real),
    [uprec] real NULL DEFAULT CAST(0 AS real),
    [uactu] real NULL DEFAULT CAST(0 AS real),
    [idtie] int NULL,
    [iqte] int NULL DEFAULT 0,
    [i2qte] decimal(18,0) NULL DEFAULT 0.0,
    [imont] decimal(18,0) NULL DEFAULT 0.0,
    [i2mont] decimal(18,0) NULL DEFAULT 0.0,
    [ivala] int NULL,
    [rvala] real NULL,
    [svala] nvarchar(200) NULL,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [mraz] int NULL DEFAULT 0,
    [araz] int NULL DEFAULT 0,
    [praz] int NULL DEFAULT 0,
    [tqan] int NULL,
    [noqan] int NULL DEFAULT 0,
    [qdat] nvarchar(20) NULL,
    [sianu] int NULL DEFAULT 0,
    [scdrub] nvarchar(50) NULL,
    [drap] nvarchar(20) NULL,
    [seqcu] int NOT NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [sict] bit NULL DEFAULT CAST(0 AS bit),
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_tiecum] PRIMARY KEY ([idcum]),
    CONSTRAINT [FK_tiecum_tiersp] FOREIGN KEY ([idtie]) REFERENCES [tiersp] ([idtie])
);
GO

CREATE TABLE [gshpst] (
    [idpst] int NOT NULL IDENTITY,
    [idhie] int NULL,
    [idzon] int NULL,
    [refa] nvarchar(5) NULL,
    [tperi] int NULL DEFAULT 0,
    [tpft] nvarchar(50) NULL,
    [tcalc] int NULL DEFAULT 1,
    [padres] nvarchar(300) NULL,
    [p2adres] nvarchar(300) NULL,
    [scdrub] nvarchar(50) NULL,
    [zcdrub] nvarchar(50) NULL DEFAULT (((0))),
    [zucdrub] nvarchar(100) NULL,
    [htyp] int NULL,
    [totyp] int NULL DEFAULT 1,
    [todir] int NULL DEFAULT 0,
    [liba] nvarchar(150) NOT NULL,
    [abg] nvarchar(25) NULL,
    [udpd] int NULL DEFAULT 0,
    [xdpd] int NULL DEFAULT 0,
    [ydpd] int NULL DEFAULT 0,
    [col] int NULL DEFAULT 0,
    [lne] int NULL DEFAULT 0,
    [eint] int NULL DEFAULT 0,
    [qnet] decimal(18,4) NULL DEFAULT 0.0,
    [qinit] decimal(18,4) NULL DEFAULT 0.0,
    [qreb] decimal(18,4) NULL DEFAULT 0.0,
    [qatt] decimal(18,4) NULL DEFAULT 0.0,
    [qat2] decimal(18,4) NULL DEFAULT 0.0,
    [emont] decimal(18,4) NULL DEFAULT 0.0,
    [e2mont] decimal(18,4) NULL DEFAULT 0.0,
    [sifin] int NULL DEFAULT 0,
    [eidrub] int NULL,
    [didpln] int NULL,
    [didrub] int NULL,
    [ztyp] int NULL DEFAULT 2,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [ixt1] int NULL DEFAULT 0,
    [operi] int NULL DEFAULT 0,
    [adseq] int NULL DEFAULT 0,
    [stdstr] nvarchar(30) NULL,
    [stfstr] nvarchar(50) NULL,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [srank] nvarchar(200) NULL,
    [irank] nvarchar(200) NULL,
    [lgtf] nvarchar(50) NULL,
    [strb] nvarchar(max) NULL,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [eta] int NULL DEFAULT 0,
    [datc] datetime2(2) NULL,
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(150) NULL,
    CONSTRAINT [PK_gshpst] PRIMARY KEY ([idpst]),
    CONSTRAINT [FK_gshpst_gshier] FOREIGN KEY ([idhie]) REFERENCES [gshier] ([idhie])
);
GO

CREATE TABLE [skpfam] (
    [idtmt] int NOT NULL IDENTITY,
    [typmt] int NULL DEFAULT 0,
    [elea] int NULL DEFAULT 0,
    [idpdt] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [idpst] int NULL DEFAULT 0,
    [stpst] nvarchar(350) NULL,
    [st2pst] nvarchar(350) NULL,
    [kprix] decimal(18,0) NULL DEFAULT 0.0,
    [mprix] decimal(18,0) NULL DEFAULT 0.0,
    [kreb] int NULL DEFAULT 0,
    [kqte] int NULL DEFAULT 0,
    [kinit] int NULL DEFAULT 0,
    [kalert] int NULL DEFAULT 0,
    [kdent] int NULL DEFAULT 0,
    [kdreb] int NULL DEFAULT 0,
    [usrid] nvarchar(450) NULL,
    [ddep] datetime2(0) NULL,
    [dfin] datetime2(0) NULL,
    [didep] int NULL DEFAULT 0,
    [difin] int NULL DEFAULT 0,
    [dope] datetime2(0) NULL DEFAULT ((getdate())),
    [datope] datetime2(0) NULL,
    [datupd] datetime2 NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 0,
    [grpe] int NULL DEFAULT 0,
    [role] int NULL DEFAULT 0,
    [roleb] int NULL DEFAULT 0,
    [styp] int NULL DEFAULT 0,
    [siscv] int NULL DEFAULT 0,
    [sioca] int NULL DEFAULT 0,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(300) NULL,
    CONSTRAINT [PK_skpfam] PRIMARY KEY ([idtmt]),
    CONSTRAINT [FK_skpfam_gshier] FOREIGN KEY ([idhie]) REFERENCES [gshier] ([idhie]),
    CONSTRAINT [FK_skpfam_skprod] FOREIGN KEY ([idpdt]) REFERENCES [skprod] ([idpdt])
);
GO

CREATE TABLE [skpmut] (
    [idtmt] int NOT NULL IDENTITY,
    [typmt] int NULL DEFAULT 0,
    [elea] int NULL DEFAULT 0,
    [idpdt] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [idpst] int NULL DEFAULT 0,
    [stpst] nvarchar(350) NULL,
    [st2pst] nvarchar(350) NULL,
    [kprix] decimal(18,0) NULL DEFAULT 0.0,
    [mprix] decimal(18,0) NULL DEFAULT 0.0,
    [kreb] int NULL DEFAULT 0,
    [kqte] int NULL DEFAULT 0,
    [kinit] int NULL DEFAULT 0,
    [kalert] int NULL DEFAULT 0,
    [kdent] int NULL DEFAULT 0,
    [kdreb] int NULL DEFAULT 0,
    [usrid] nvarchar(450) NULL,
    [ddep] datetime2(0) NULL,
    [dfin] datetime2(0) NULL,
    [didep] int NULL DEFAULT 0,
    [difin] int NULL DEFAULT 0,
    [dope] datetime2(0) NULL DEFAULT ((getdate())),
    [datope] datetime2(0) NULL,
    [datupd] datetime2 NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 0,
    [grpe] int NULL DEFAULT 0,
    [role] int NULL DEFAULT 0,
    [roleb] int NULL DEFAULT 0,
    [styp] int NULL DEFAULT 0,
    [siscv] int NULL DEFAULT 0,
    [sioca] int NULL DEFAULT 0,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(300) NULL,
    CONSTRAINT [PK_skpmut] PRIMARY KEY ([idtmt]),
    CONSTRAINT [FK_skpmut_gshier] FOREIGN KEY ([idhie]) REFERENCES [gshier] ([idhie]),
    CONSTRAINT [FK_skpmut_skprod] FOREIGN KEY ([idpdt]) REFERENCES [skprod] ([idpdt])
);
GO

CREATE TABLE [actsaie] (
    [idact] int NOT NULL IDENTITY,
    [idtie] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [plngri] int NULL DEFAULT 0,
    [plnpln] int NULL DEFAULT 0,
    [plnpgr] int NULL DEFAULT 0,
    [idrub] int NULL DEFAULT 0,
    [grirub] int NULL DEFAULT 0,
    [pgrub] int NULL DEFAULT 0,
    [pgrrub] int NULL DEFAULT 0,
    [ordac] int NULL DEFAULT 0,
    [sidet] int NULL DEFAULT 0,
    [scdrub] nvarchar(50) NULL,
    [scdzon] int NULL DEFAULT 0,
    [detseq] int NULL DEFAULT 0,
    [slgrub] nvarchar(150) NULL,
    [svala] nvarchar(150) NULL,
    [refa] nvarchar(25) NULL,
    [eidrub] int NULL,
    [smatri] nvarchar(50) NULL,
    [iguic] int NULL DEFAULT 0,
    [atyp] int NULL DEFAULT 0,
    [ivala] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [ddval] datetime2(0) NULL,
    [dfval] datetime2(0) NULL,
    [tperi] int NULL DEFAULT 0,
    [kcqte] int NULL DEFAULT 0,
    [kcprix] decimal(18,4) NULL DEFAULT 0.0,
    [kcvala] decimal(18,4) NULL DEFAULT 0.0,
    [rsens] int NULL DEFAULT 0,
    [vhtx] decimal(18,4) NULL DEFAULT 0.0,
    [vtax] decimal(18,4) NULL DEFAULT 0.0,
    [vtva] decimal(18,4) NULL DEFAULT 0.0,
    [vred] decimal(18,4) NULL DEFAULT 0.0,
    [vdiv] decimal(18,4) NULL DEFAULT 0.0,
    [vtht] decimal(18,4) NULL DEFAULT 0.0,
    [vttc] decimal(18,4) NULL DEFAULT 0.0,
    [vnet] decimal(18,4) NULL DEFAULT 0.0,
    [idzon] int NULL DEFAULT 0,
    [evala] decimal(18,4) NULL DEFAULT 0.0,
    [fvala] float NULL DEFAULT 0.0E0,
    [elea] int NULL DEFAULT 0,
    [igpe] int NULL DEFAULT 0,
    [sigrid] int NULL DEFAULT 0,
    [siope] int NULL DEFAULT 0,
    [emont] decimal(18,4) NULL DEFAULT 0.0,
    [esolde] decimal(18,4) NULL DEFAULT 0.0,
    [ecredi] decimal(18,4) NULL DEFAULT 0.0,
    [edebi] decimal(18,4) NULL DEFAULT 0.0,
    [eanui] decimal(18,4) NULL DEFAULT 0.0,
    [nbtot] int NULL DEFAULT 0,
    [nbsld] int NULL DEFAULT 0,
    [eddat] datetime2(2) NULL,
    [efdat] datetime2(2) NULL,
    [tcorig] int NULL DEFAULT 0,
    [ecorig] decimal(18,4) NULL DEFAULT 0.0,
    [m9anui] decimal(18,4) NULL DEFAULT 0.0,
    [blksess] int NULL,
    [blksaie] int NULL DEFAULT 0,
    [blkcalc] int NULL,
    [aorig] int NULL DEFAULT 0,
    [tvers] int NULL DEFAULT 0,
    [froac] int NULL DEFAULT 0,
    [sifin] int NULL DEFAULT 0,
    [tope] int NULL DEFAULT 0,
    [jour] int NULL DEFAULT 0,
    [mois] int NULL DEFAULT 0,
    [an] int NULL DEFAULT 0,
    [eta] int NULL DEFAULT 0,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [datu] datetime2(2) NULL,
    [usrmin] nvarchar(450) NULL,
    [usris2] nvarchar(450) NULL,
    [usris3] nvarchar(450) NULL,
    [usris4] datetime2 NULL,
    [udmin] datetime2(0) NULL,
    [udis2] datetime2(0) NULL,
    [udis3] datetime2(0) NULL,
    [udis4] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_actsaie] PRIMARY KEY ([idact]),
    CONSTRAINT [FK_actsaie_rubvar] FOREIGN KEY ([idrub]) REFERENCES [rubvar] ([idrub]),
    CONSTRAINT [FK_actsaie_tiersp] FOREIGN KEY ([idtie]) REFERENCES [tiersp] ([idtie])
);
GO

CREATE TABLE [gscpt] (
    [idcpt] int NOT NULL IDENTITY,
    [tovers] int NULL DEFAULT 1,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [idrub] int NULL,
    [nostr] nvarchar(50) NULL,
    [sctrub] nvarchar(150) NULL,
    [operi] int NULL DEFAULT 0,
    [opdat] datetime2(2) NULL,
    [debit] real NULL,
    [credit] real NULL,
    [solde] real NULL,
    [attend] real NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [sict] bit NULL DEFAULT CAST(0 AS bit),
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_gscpt] PRIMARY KEY ([idcpt]),
    CONSTRAINT [FK_gscpt_gxorga] FOREIGN KEY ([idorg]) REFERENCES [gxorga] ([idorg]) ON DELETE CASCADE,
    CONSTRAINT [FK_gscpt_rubvar] FOREIGN KEY ([idrub]) REFERENCES [rubvar] ([idrub])
);
GO

CREATE TABLE [gscum] (
    [idcum] int NOT NULL IDENTITY,
    [tovers] int NULL DEFAULT 1,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [idfed] int NULL DEFAULT 0,
    [idsuc] int NULL DEFAULT 9,
    [idmvt] int NULL DEFAULT 0,
    [operi] int NULL DEFAULT 0,
    [otyp] int NULL,
    [nostr] nvarchar(50) NULL,
    [pidpln] int NULL,
    [idrub] int NULL,
    [ucdcu] nvarchar(50) NULL,
    [uante] real NULL DEFAULT CAST(0 AS real),
    [uprec] real NULL DEFAULT CAST(0 AS real),
    [uactu] real NULL DEFAULT CAST(0 AS real),
    [ivala] int NULL,
    [rvala] real NULL,
    [svala] nvarchar(200) NULL,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [mraz] int NULL DEFAULT 0,
    [araz] int NULL DEFAULT 0,
    [praz] int NULL DEFAULT 0,
    [tqan] int NULL,
    [noqan] int NULL DEFAULT 0,
    [qdat] nvarchar(20) NULL,
    [sianu] int NULL DEFAULT 0,
    [scdrub] nvarchar(50) NULL,
    [drap] nvarchar(20) NULL,
    [seqcu] int NOT NULL,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [sict] bit NULL DEFAULT CAST(0 AS bit),
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_gscum] PRIMARY KEY ([idcum]),
    CONSTRAINT [FK_gscum_gxorga] FOREIGN KEY ([idorg]) REFERENCES [gxorga] ([idorg]),
    CONSTRAINT [FK_gscum_rubvar] FOREIGN KEY ([idrub]) REFERENCES [rubvar] ([idrub])
);
GO

CREATE TABLE [resbro] (
    [idres] int NOT NULL IDENTITY,
    [operi] int NOT NULL,
    [idtie] int NOT NULL,
    [ucdres] nvarchar(100) NOT NULL,
    [nopai] int NOT NULL,
    [matri] nvarchar(50) NULL,
    [idrub] int NULL DEFAULT 0,
    [idzon] int NULL DEFAULT 0,
    [idact] int NULL DEFAULT 0,
    [ordac] int NULL DEFAULT 0,
    [rcdrub] nvarchar(50) NULL,
    [zcdrub] nvarchar(50) NULL,
    [utyp] int NULL DEFAULT 0,
    [plngri] int NULL DEFAULT 0,
    [plnpln] int NULL DEFAULT 0,
    [plnpgr] int NULL DEFAULT 0,
    [plnrub] int NULL DEFAULT 0,
    [pgrrub] int NULL DEFAULT 0,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] decimal(18,4) NULL DEFAULT 0.0,
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [tperi] int NULL DEFAULT 1,
    [kcqte] int NULL DEFAULT 0,
    [kcprix] decimal(18,4) NULL DEFAULT 0.0,
    [kcvala] decimal(18,4) NULL DEFAULT 0.0,
    [rsens] int NULL DEFAULT 0,
    [vhtx] decimal(18,4) NULL DEFAULT 0.0,
    [vtax] decimal(18,4) NULL DEFAULT 0.0,
    [vtva] decimal(18,4) NULL DEFAULT 0.0,
    [vred] decimal(18,4) NULL DEFAULT 0.0,
    [vdiv] decimal(18,4) NULL DEFAULT 0.0,
    [vtht] decimal(18,4) NULL DEFAULT 0.0,
    [vttc] decimal(18,4) NULL DEFAULT 0.0,
    [vnet] decimal(18,4) NULL DEFAULT 0.0,
    [indat] int NULL DEFAULT 0,
    [ordfi] int NULL DEFAULT 0,
    [strdiv] nvarchar(100) NULL,
    [evala] decimal(18,3) NULL DEFAULT 0.0,
    [fvala] float NULL DEFAULT 0.0E0,
    [ecpris] int NULL DEFAULT 0,
    [rorig] int NULL DEFAULT 1,
    [ridzon] int NULL DEFAULT 0,
    [cpre] nvarchar(5) NULL,
    [typb] int NULL DEFAULT 0,
    [strmx] nvarchar(max) NULL,
    [froac] int NULL DEFAULT 0,
    [rmatri] nvarchar(50) NOT NULL,
    [sidet] int NULL DEFAULT 0,
    [rihie] int NULL DEFAULT 0,
    [strb] nvarchar(250) NULL,
    [jour] int NULL DEFAULT 0,
    [mois] int NULL DEFAULT 0,
    [an] int NULL DEFAULT 0,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [idorg] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [eta] int NULL DEFAULT 0,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_resbro] PRIMARY KEY ([idres]),
    CONSTRAINT [FK_resbro_rubvar] FOREIGN KEY ([idrub]) REFERENCES [rubvar] ([idrub]),
    CONSTRAINT [FK_resbro_tiersp] FOREIGN KEY ([idtie]) REFERENCES [tiersp] ([idtie])
);
GO

CREATE TABLE [rubfmt] (
    [idrub] int NOT NULL,
    [idzon] int NOT NULL,
    [refa] nvarchar(5) NULL,
    [tperi] int NULL DEFAULT 0,
    [tpft] nvarchar(50) NULL,
    [tcalc] int NULL DEFAULT 1,
    [scdrub] nvarchar(50) NULL,
    [zcdrub] nvarchar(50) NULL DEFAULT (((0))),
    [zucdrub] nvarchar(100) NULL,
    [htyp] int NULL,
    [totyp] int NULL DEFAULT 1,
    [todir] int NULL DEFAULT 0,
    [liba] nvarchar(150) NOT NULL,
    [abg] nvarchar(25) NULL,
    [ftsource] nvarchar(max) NULL,
    [udpd] int NULL DEFAULT 0,
    [xdpd] int NULL DEFAULT 0,
    [ydpd] int NULL DEFAULT 0,
    [col] int NULL DEFAULT 0,
    [lne] int NULL DEFAULT 0,
    [eint] int NULL DEFAULT 0,
    [e2int] int NULL DEFAULT 0,
    [emont] decimal(18,4) NULL DEFAULT 0.0,
    [e2mont] decimal(18,4) NULL DEFAULT 0.0,
    [sifin] int NULL DEFAULT 0,
    [eidrub] int NULL,
    [didpln] int NULL,
    [didrub] int NULL,
    [ztyp] int NULL DEFAULT 2,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [ixt1] int NULL DEFAULT 0,
    [operi] int NULL DEFAULT 0,
    [adseq] int NULL DEFAULT 0,
    [stdstr] nvarchar(30) NULL,
    [stfstr] nvarchar(50) NULL,
    [dtdval] int NULL DEFAULT 0,
    [dtfval] int NULL DEFAULT 0,
    [srank] nvarchar(200) NULL,
    [irank] nvarchar(200) NULL,
    [lgt1] int NULL DEFAULT 0,
    [lgtf] nvarchar(50) NULL,
    [strb] nvarchar(max) NULL,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [eta] int NULL DEFAULT 0,
    [datc] datetime2(2) NULL,
    [datu] datetime2(0) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(150) NULL,
    CONSTRAINT [PK_rubfmt] PRIMARY KEY ([idrub], [idzon]),
    CONSTRAINT [FK_rubfmt_rubvar] FOREIGN KEY ([idrub]) REFERENCES [rubvar] ([idrub])
);
GO

CREATE TABLE [resdet] (
    [idres] int NOT NULL,
    [idlne] int NOT NULL,
    [operi] int NOT NULL,
    [idtie] int NOT NULL,
    [nopai] int NOT NULL,
    [pidpln] int NULL DEFAULT 0,
    [pidrub] int NULL DEFAULT 0,
    [utyp] int NULL DEFAULT 0,
    [putyp] int NULL DEFAULT 0,
    [svala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] real NULL DEFAULT CAST(0 AS real),
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [evala] decimal(18,0) NULL DEFAULT 0.0,
    [fvala] float NULL DEFAULT 0.0E0,
    [vhtx] decimal(3,0) NULL DEFAULT 0.0,
    [vtax] decimal(3,0) NULL DEFAULT 0.0,
    [vtva] decimal(3,0) NULL DEFAULT 0.0,
    [vred] decimal(3,0) NULL DEFAULT 0.0,
    [vdiv] decimal(3,0) NULL DEFAULT 0.0,
    [vtht] decimal(3,0) NULL DEFAULT 0.0,
    [vttc] decimal(3,0) NULL DEFAULT 0.0,
    [vnet] decimal(3,0) NULL DEFAULT 0.0,
    [ddatc] datetime2(2) NULL DEFAULT ((getdate())),
    [idzon] int NULL DEFAULT 0,
    [cod2] nvarchar(50) NULL,
    [tyre] int NULL DEFAULT 0,
    [strb] nvarchar(max) NULL,
    [jour] int NULL DEFAULT 0,
    [mois] int NULL DEFAULT 0,
    [an] int NULL DEFAULT 0,
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_resdet_1] PRIMARY KEY ([idres], [idlne]),
    CONSTRAINT [FK_resdet_resdon] FOREIGN KEY ([idres]) REFERENCES [resdon] ([idres])
);
GO

CREATE TABLE [tiemut] (
    [idtmt] int NOT NULL IDENTITY,
    [typmt] int NULL DEFAULT 0,
    [elea] int NULL DEFAULT 0,
    [idtie] int NULL DEFAULT 0,
    [idhie] int NULL DEFAULT 0,
    [idpst] int NULL DEFAULT 0,
    [stpst] nvarchar(350) NULL,
    [st2pst] nvarchar(350) NULL,
    [usrid] nvarchar(450) NULL,
    [kprix] decimal(18,0) NULL DEFAULT 0.0,
    [mprix] decimal(18,0) NULL,
    [kreb] int NULL DEFAULT 0,
    [kqte] int NULL DEFAULT 0,
    [kinit] int NULL DEFAULT 0,
    [kalert] int NULL DEFAULT 0,
    [kdent] int NULL DEFAULT 0,
    [kdreb] int NULL DEFAULT 0,
    [ddep] datetime2(0) NULL,
    [dfin] datetime2(0) NULL,
    [didep] int NULL DEFAULT 0,
    [difin] int NULL DEFAULT 0,
    [dope] datetime2(0) NULL DEFAULT ((getdate())),
    [datope] datetime2(0) NULL,
    [datupd] datetime2 NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 0,
    [grpe] int NULL DEFAULT 0,
    [role] int NULL DEFAULT 0,
    [roleb] int NULL DEFAULT 0,
    [styp] int NULL DEFAULT 0,
    [siscv] int NULL DEFAULT 0,
    [sioca] int NULL DEFAULT 0,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(300) NULL,
    CONSTRAINT [PK_tiemut] PRIMARY KEY ([idtmt]),
    CONSTRAINT [FK_tiemut_gshier] FOREIGN KEY ([idhie]) REFERENCES [gshier] ([idhie]),
    CONSTRAINT [FK_tiemut_gshpst] FOREIGN KEY ([idpst]) REFERENCES [gshpst] ([idpst]),
    CONSTRAINT [FK_tiemut_tiersp] FOREIGN KEY ([idtie]) REFERENCES [tiersp] ([idtie])
);
GO

CREATE TABLE [actdet] (
    [idact] int NOT NULL,
    [dseq] int NOT NULL,
    [idtie] int NULL DEFAULT 0,
    [ucdact] nvarchar(100) NULL,
    [acdrub] nvarchar(50) NULL,
    [zcdrub] nvarchar(50) NULL,
    [idrub] int NULL DEFAULT 0,
    [ipgrub] int NULL DEFAULT 0,
    [igdrub] int NULL DEFAULT 0,
    [plnpln] int NULL DEFAULT 0,
    [plirub] int NULL DEFAULT 0,
    [plifmt] int NULL DEFAULT 0,
    [smatri] nvarchar(50) NOT NULL,
    [etyp] int NULL DEFAULT 0,
    [svala] nvarchar(150) NULL,
    [s2vala] nvarchar(150) NULL,
    [ivala] int NULL DEFAULT 0,
    [rvala] decimal(18,3) NULL DEFAULT 0.0,
    [bvala] bit NULL DEFAULT CAST(0 AS bit),
    [dvala] datetime2(2) NULL,
    [ndval] int NULL DEFAULT 0,
    [evala] decimal(18,4) NULL DEFAULT 0.0,
    [fvala] float NULL DEFAULT 0.0E0,
    [kcqte] int NULL DEFAULT 0,
    [kcprix] decimal(18,4) NULL DEFAULT 0.0,
    [kcvala] decimal(18,4) NULL DEFAULT 0.0,
    [rsens] int NULL DEFAULT 0,
    [vhtx] decimal(18,4) NULL DEFAULT 0.0,
    [vtax] decimal(18,4) NULL DEFAULT 0.0,
    [vtva] decimal(18,4) NULL DEFAULT 0.0,
    [vred] decimal(18,4) NULL DEFAULT 0.0,
    [vdiv] decimal(18,4) NULL DEFAULT 0.0,
    [vtht] decimal(18,4) NULL DEFAULT 0.0,
    [vttc] decimal(18,4) NULL DEFAULT 0.0,
    [vnet] decimal(18,4) NULL DEFAULT 0.0,
    [operi] int NULL DEFAULT 0,
    [idval] int NULL DEFAULT 0,
    [ifval] int NULL DEFAULT 0,
    [ddval] datetime2(0) NULL,
    [dfval] datetime2(0) NULL,
    [tperi] int NULL DEFAULT 0,
    [ncredi] decimal(18,4) NULL DEFAULT 0.0,
    [ndebi] decimal(18,4) NULL DEFAULT 0.0,
    [nsolde] decimal(18,4) NULL DEFAULT 0.0,
    [nddat] decimal(18,4) NULL,
    [nfdat] datetime2(2) NULL,
    [froac] int NULL DEFAULT 0,
    [sifin] int NULL DEFAULT 0,
    [tope] int NULL DEFAULT 0,
    [dstr] nvarchar(80) NULL,
    [fstr] nvarchar(80) NULL,
    [d2str] nvarchar(80) NULL,
    [f2str] nvarchar(80) NULL,
    [drel] real NULL DEFAULT CAST(0 AS real),
    [frel] real NULL DEFAULT CAST(0 AS real),
    [dint] int NULL DEFAULT 0,
    [fint] int NULL DEFAULT 0,
    [ddat] int NULL,
    [fdat] int NULL,
    [jour] int NULL DEFAULT 0,
    [mois] int NULL DEFAULT 0,
    [an] int NULL DEFAULT 0,
    [eta] int NULL DEFAULT 0,
    [siv] bit NULL DEFAULT CAST(0 AS bit),
    [selc] bit NULL DEFAULT CAST(0 AS bit),
    [datc] datetime2(2) NULL DEFAULT ((getdate())),
    [datu] datetime2(0) NULL,
    [udmin] datetime2(0) NULL,
    [usrmin] nvarchar(450) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_actdet] PRIMARY KEY ([idact], [dseq]),
    CONSTRAINT [FK_actdet_actsaie] FOREIGN KEY ([idact]) REFERENCES [actsaie] ([idact])
);
GO

CREATE TABLE [gsctne] (
    [idclne] int NOT NULL IDENTITY,
    [idcpt] int NULL,
    [ctlne] int NULL DEFAULT 0,
    [attmont] decimal(18,0) NOT NULL,
    [datp] datetime2(2) NULL,
    [recmont] decimal(18,0) NULL DEFAULT 0.0,
    [solde] decimal(18,0) NULL DEFAULT 0.0,
    [idval] datetime2(2) NULL,
    [ifval] datetime2(2) NULL,
    [methp] int NULL DEFAULT 0,
    [payref] nvarchar(200) NULL,
    [scdrub] nvarchar(50) NULL,
    [totyp] int NULL DEFAULT 1,
    [liba] nvarchar(80) NULL,
    [abg] nvarchar(25) NULL,
    [refa] nvarchar(50) NULL,
    [gtyp] int NULL DEFAULT 0,
    [lgcdrub] nvarchar(50) NULL,
    [uraz] int NULL DEFAULT 0,
    [svala] nvarchar(150) NULL,
    [usrope] nvarchar(450) NULL,
    [usrupd] nvarchar(450) NULL,
    [ivalid] int NULL DEFAULT 9,
    [iclos] int NULL DEFAULT 9,
    [eta] int NULL DEFAULT 0,
    [eaut] int NULL DEFAULT 0,
    [obsv] nvarchar(250) NULL,
    CONSTRAINT [PK_gsctne] PRIMARY KEY ([idclne]),
    CONSTRAINT [FK_gsctne_gscpt] FOREIGN KEY ([idcpt]) REFERENCES [gscpt] ([idcpt])
);
GO

CREATE INDEX [IX_actsaie_idrub] ON [actsaie] ([idrub]);
GO

CREATE INDEX [IX_actsaie_idtie] ON [actsaie] ([idtie]);
GO

CREATE INDEX [IX_dicpro_mosq] ON [dicpro] ([mosq]);
GO

CREATE INDEX [IX_gsapl_idorg] ON [gsapl] ([idorg]);
GO

CREATE INDEX [IX_gscpt_idorg] ON [gscpt] ([idorg]);
GO

CREATE INDEX [IX_gscpt_idrub] ON [gscpt] ([idrub]);
GO

CREATE INDEX [IX_gsctne_idcpt] ON [gsctne] ([idcpt]);
GO

CREATE INDEX [IX_gscum_idorg] ON [gscum] ([idorg]);
GO

CREATE INDEX [IX_gscum_idrub] ON [gscum] ([idrub]);
GO

CREATE INDEX [IX_gsessu_idpln] ON [gsessu] ([idpln]);
GO

CREATE INDEX [IX_gsgfix_idorg] ON [gsgfix] ([idorg]);
GO

CREATE INDEX [IX_gshier_idpln] ON [gshier] ([idpln]);
GO

CREATE INDEX [IX_gshpst_idhie] ON [gshpst] ([idhie]);
GO

CREATE INDEX [IX_ocmde_idtiw] ON [ocmde] ([idtiw]);
GO

CREATE INDEX [IX_ojgen_idorg] ON [ojgen] ([idorg]);
GO

CREATE INDEX [IX_plngen_idorg] ON [plngen] ([idorg]);
GO

CREATE INDEX [IX_resbro_idrub] ON [resbro] ([idrub]);
GO

CREATE INDEX [IX_resbro_idtie] ON [resbro] ([idtie]);
GO

CREATE INDEX [IX_resdon_idtie] ON [resdon] ([idtie]);
GO

CREATE INDEX [IX_rubvar_idpln] ON [rubvar] ([idpln]);
GO

CREATE INDEX [IX_skpfam_idhie] ON [skpfam] ([idhie]);
GO

CREATE INDEX [IX_skpfam_idpdt] ON [skpfam] ([idpdt]);
GO

CREATE INDEX [IX_skpmut_idhie] ON [skpmut] ([idhie]);
GO

CREATE INDEX [IX_skpmut_idpdt] ON [skpmut] ([idpdt]);
GO

CREATE INDEX [IX_skprod_idorg] ON [skprod] ([idorg]);
GO

CREATE INDEX [IX_tieafil_idtie] ON [tieafil] ([idtie]);
GO

CREATE INDEX [IX_tieapl_idtie] ON [tieapl] ([idtie]);
GO

CREATE INDEX [IX_tiecpt_idtie] ON [tiecpt] ([idtie]);
GO

CREATE INDEX [IX_tiecum_idtie] ON [tiecum] ([idtie]);
GO

CREATE INDEX [IX_tiemut_idhie] ON [tiemut] ([idhie]);
GO

CREATE INDEX [IX_tiemut_idpst] ON [tiemut] ([idpst]);
GO

CREATE INDEX [IX_tiemut_idtie] ON [tiemut] ([idtie]);
GO

CREATE INDEX [IX_tiersp_idorg] ON [tiersp] ([idorg]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20250120084455_kad11', N'8.0.11');
GO

COMMIT;
GO

